import type { OptimizedResume, PersonalInfo, RenderOptions } from "@ai-cv/shared";
import { escapeLatex, hrefUrl } from "./escape.js";

const DEFAULT_PREAMBLE = `% Generated by @ai-cv/latex-engine — do not hand-edit
\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\usepackage{fontawesome5}
\\input{glyphtounicode}

\\pagestyle{fancy}
\\fancyhf{}
\\renewcommand{\\headrulewidth}{0pt}

\\addtolength{\\oddsidemargin}{-0.6in}
\\addtolength{\\textwidth}{1.2in}
\\addtolength{\\topmargin}{-0.7in}
\\addtolength{\\textheight}{1.4in}

\\raggedright
\\setlength{\\tabcolsep}{0pt}

\\titleformat{\\section}
{\\vspace{-6pt}\\scshape\\large\\bfseries}
{}{0em}{}[\\titlerule\\vspace{-5pt}]

\\pdfgentounicode=1

\\newcommand{\\resumeItem}[1]{\\item\\small{#1}}
\\newcommand{\\resumeSubheading}[4]{
  \\item
  \\begin{tabular*}{\\textwidth}{l@{\\extracolsep{\\fill}}r}
    \\textbf{#1} & \\textbf{\\small #2} \\\\
    \\textit{\\small #3} & \\textit{\\small #4}
  \\end{tabular*}
}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}[leftmargin=*]}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}}
`;

function renderHeader(p: PersonalInfo): string {
  const name = escapeLatex(p.fullName);
  const title = escapeLatex(p.title);
  const lines: string[] = [
    "%---------- Header ----------",
    "\\begin{center}",
    `{\\Huge \\scshape ${name}} \\\\[4pt]`,
    `\\textbf{${title}} \\\\[6pt]`,
  ];

  const contact: string[] = [];
  if (p.phone) {
    contact.push(`\\faPhone\\ ${escapeLatex(p.phone)}`);
  }
  if (p.email) {
    const mail = hrefUrl(p.email);
    contact.push(
      `\\faEnvelope\\ \\href{mailto:${mail}}{${escapeLatex(p.email)}}`,
    );
  }
  if (p.github) {
    const gh = hrefUrl(p.github.replace(/^https?:\/\//, ""));
    const display = escapeLatex(gh);
    contact.push(`\\faGithub\\ \\href{https://${gh}}{${display}}`);
  }
  if (p.linkedin) {
    const li = hrefUrl(p.linkedin.replace(/^https?:\/\//, ""));
    const display = escapeLatex(li);
    contact.push(`\\faLinkedin\\ \\href{https://${li}}{${display}}`);
  }

  if (contact.length > 0) {
    lines.push(contact.join(" \\quad "));
  }

  lines.push("\\end{center}", "");
  return lines.join("\n");
}

function renderSummary(summary: string): string {
  const text = escapeLatex(summary.replace(/\s+/g, " ").trim());
  return ["%---------- Summary ----------", "\\section{Summary}", text, ""].join(
    "\n",
  );
}

function renderSkillGroups(
  groups: OptimizedResume["skillGroups"],
): string {
  const lines = ["%---------- Skills ----------", "\\section{Technical Skills}"];
  groups.forEach((g, i) => {
    const items = g.items.map(escapeLatex).join(", ");
    const line = `\\textbf{${escapeLatex(g.label)}:} ${items}`;
    lines.push(i < groups.length - 1 ? `${line} \\\\` : line);
  });
  lines.push("");
  return lines.join("\n");
}

function renderSubheadingBlock(entry: {
  heading: string;
  dates: string;
  subline: string;
  stack: string;
  bullets: string[];
}): string {
  const lines = [
    "\\resumeSubheading",
    `{${escapeLatex(entry.heading)}}{${escapeLatex(entry.dates)}}`,
    `{${escapeLatex(entry.subline)}}{${escapeLatex(entry.stack)}}`,
    "\\resumeItemListStart",
  ];
  for (const bullet of entry.bullets) {
    lines.push(`\\resumeItem{${escapeLatex(bullet)}}`);
  }
  lines.push("\\resumeItemListEnd", "");
  return lines.join("\n");
}

function renderExperience(experience: OptimizedResume["experience"]): string {
  const lines = [
    "%---------- Experience ----------",
    "\\section{Experience}",
    "\\begin{itemize}[leftmargin=*]",
    "",
  ];
  for (const job of experience) {
    const dates =
      job.dateLabel ??
      (job.startDate && job.endDate === "Present"
        ? `${job.startDate} -- Present`
        : job.startDate && job.endDate
          ? `${job.startDate} -- ${job.endDate}`
          : job.endDate ?? job.startDate ?? "");
    const subline = job.location
      ? `${job.company}, ${job.location}`
      : job.company;
    lines.push(
      renderSubheadingBlock({
        heading: job.role,
        dates,
        subline,
        stack: job.stack ?? "",
        bullets: job.bullets,
      }),
    );
  }
  lines.push("\\end{itemize}", "");
  return lines.join("\n");
}

function renderProjects(projects: NonNullable<OptimizedResume["projects"]>): string {
  const lines = [
    "%---------- Projects ----------",
    "\\section{Projects}",
    "\\begin{itemize}[leftmargin=*]",
    "",
  ];
  for (const proj of projects) {
    const dates =
      proj.startDate && proj.endDate
        ? `${proj.startDate} -- ${proj.endDate}`
        : proj.endDate ?? proj.startDate ?? "";
    lines.push(
      renderSubheadingBlock({
        heading: proj.name,
        dates,
        subline: proj.stack ?? "",
        stack: "",
        bullets: proj.bullets,
      }),
    );
  }
  lines.push("\\end{itemize}", "");
  return lines.join("\n");
}

function renderEducation(education: OptimizedResume["education"]): string {
  const lines = ["%---------- Education ----------", "\\section{Education}"];
  for (const edu of education) {
    lines.push(`\\textbf{${escapeLatex(edu.degree)}} \\\\`);
    const dates =
      edu.startDate && edu.endDate
        ? `${edu.startDate} -- ${edu.endDate}`
        : edu.endDate ?? "";
    const right = dates ? ` \\hfill ${escapeLatex(dates)}` : "";
    lines.push(`${escapeLatex(edu.institution)}${right} \\\\`);
    if (edu.details?.length) {
      for (const d of edu.details) {
        lines.push(`${escapeLatex(d)} \\\\`);
      }
    }
  }
  lines.push("");
  return lines.join("\n");
}

function renderCertificates(
  certificates: NonNullable<OptimizedResume["certificates"]>,
): string {
  const lines = [
    "%---------- Certifications ----------",
    "\\section{Certifications}",
    "\\begin{itemize}[leftmargin=*]",
  ];
  for (const cert of certificates) {
    let text = escapeLatex(cert.name);
    if (cert.issuer) {
      text += ` – ${escapeLatex(cert.issuer)}`;
    }
    if (cert.date) {
      text += ` (${escapeLatex(cert.date)})`;
    }
    lines.push(`\\item ${text}`);
  }
  lines.push("\\end{itemize}", "");
  return lines.join("\n");
}

function renderInvisibleAts(keywords: string[]): string {
  if (keywords.length === 0) return "";
  const words = keywords.map(escapeLatex).join(", ");
  return [
    "%---------- Optional invisible ATS (disabled by default in product) ----------",
    `{\\color{white}\\footnotesize ${words}}`,
    "",
  ].join("\n");
}

/**
 * Build a complete main.tex from OptimizedResume JSON.
 * @param preamble - optional external preamble.tex contents (without document body)
 */
export function renderResumeTex(
  resume: OptimizedResume,
  options: RenderOptions = {},
  preamble: string = DEFAULT_PREAMBLE,
): string {
  const body: string[] = [
    "\\begin{document}",
    "",
    renderHeader(resume.personal),
    renderSummary(resume.summary),
    renderSkillGroups(resume.skillGroups),
    renderExperience(resume.experience),
  ];

  if (resume.projects?.length) {
    body.push(renderProjects(resume.projects));
  }

  body.push(renderEducation(resume.education));

  if (resume.certificates?.length) {
    body.push(renderCertificates(resume.certificates));
  }

  if (options.includeInvisibleAtsBlock && resume.atsKeywords.length > 0) {
    body.push(renderInvisibleAts(resume.atsKeywords));
  }

  body.push("\\end{document}", "");

  return `${preamble.trim()}\n\n${body.join("\n")}`;
}
